apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}

data:
  APPLICATION_NAME: {{ .Values.applicationName | default "notification" }}

  SPRING_DATASOURCE_URL: {{ tpl .Values.database.url  . | required "database.url is required" }}