image:
  repository: exchange-service
  pullPolicy: IfNotPresent
  tag: 0.0.1-SNAPSHOT
  
replicaCount: 1

server:
  port: 8080

oauth2:
  clientSecret: HNY8Fym1iF9LsprSS9v7YvErYfJKEYmp

database:
  url: "jdbc:postgresql://{{ .Release.Name }}-exchange-db:5432/exchange_db"
  username: postgres
  password: postgres
  
service:
  type: ClusterIP
  port: 8080 
  
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""  
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  