server:
  port: 8088

spring:
  application:
    name: notification-service
  config:
    import: classpath:application-common.yml

  security:
    oauth2:
      client:
        registration:
          bank:
            client-id: notification-client
            client-secret: VMZHtTUfL9QeQD2KTdK2UWJrc13weZE6
  mail:
    host: smtp.gmail.com
    port: 587
    username: your.email@gmail.com
    password: app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
