package com.alextim.bank.common.constant;


public enum EventType {

    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_PASSWORD_CHANGED,
    ACCOUNT_LOGIN,
    ACCOUNT_LOGIN_FAILED,
    ACCOUNT_DELETED,
    ACCOUNT_BALANCE_UPDATED,


    BALANCE_CREDITED,   // зачисление
    BALANCE_DEBITED,    // списание
    BALANCE_TRANSFERRED_INTERNAL,
    BALANCE_TRANSFERRED_EXTERNAL,

    CURRENCY_CONVERTED,

    CASH_DEPOSIT,
    CASH_WITHDRAW,

    SUSPICIOUS_OPERATION_DETECTED,
    ACCOUNT_BLOCKED,
    OPERATION_BLOCKED,

    EXCHANGE_RATES_UPDATED,
}