apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui-service.fullname" . }}
  labels:
    {{- include "front-ui-service.labels" . | nindent 4 }}

data:
  APPLICATION_NAME: {{ .Values.applicationName | default "front-ui" }}