apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}

data:
  APPLICATION_NAME: account
  SPRING_DATASOURCE_URL: {{ tpl .Values.database.url . | required "database.url is required" }}

  REDIS_HOST: {{ tpl .Values.redis.host  . | required "redis.host is required" }}
  REDIS_PORT: "{{ .Values.redis.port | required "redis.host is required" }}"
