apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}

data:
  APPLICATION_NAME: cash
  SPRING_DATASOURCE_URL: {{ tpl .Values.database.url  .  | required "database.url is required" }}