{{- if .Values.logstash.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-logstash-config
  labels:
    app: logstash
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.enabled: false
  logstash.conf: |
{{ tpl .Values.logstash.config . | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-logstash
  labels:
    app: logstash
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ .Values.logstash.service.port }}
      targetPort: 9600
  selector:
    app: logstash
    release: "{{ .Release.Name }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logstash
  labels:
    app: logstash
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: logstash
        release: "{{ .Release.Name }}"
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.logstash.image }}:{{ .Values.logstash.imageTag }}"
          imagePullPolicy: {{ .Values.logstash.imagePullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 9600
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config-volume
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          resources:
{{ toYaml .Values.logstash.resources | indent 10 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-logstash-config
{{- end }}