image:
  repository: blocker-service
  pullPolicy: IfNotPresent
  tag: 0.0.1-SNAPSHOT

replicaCount: 1

server:
  port: 8080

oauth2:
  clientSecret: OOwYJIcXl9Yf7HbbCdygEt3JmlBJrMYo

database:
  url: "jdbc:postgresql://{{ .Release.Name }}-suspicious-operation-db:5432/suspicious_operation_db"
  username: postgres
  password: postgres
  
redis:
  host: "{{ .Release.Name }}-operation-count-db-master"
  port: 6379

service:
  type: ClusterIP
  port: 8080 
  
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""  
  
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
   