server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alextim1508/bank-config
          refreshRate: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,env