apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generator-service.fullname" . }}
  labels:
    {{- include "exchange-generator-service.labels" . | nindent 4 }}
    
data:
  SECURITY_OAUTH2_CLIENT_REGISTRATION_BANK_TOKEN_URL: {{ tpl .Values.oauth2.clientRegistrationBankTokenUrl  .  | required "oauth2.clientRegistrationBankTokenUrl is required" }}
  KAFKA_BOOTSTRAP_SERVERS: {{ tpl .Values.kafka.bootstarServers  .  | required "kafka.bootstarServers is required" }}